<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Achievement;

class AchievementSeeder extends Seeder
{
    public function run(): void
    {
        $achievements = [
            [
                'slug' => 'first_blood',
                'name' => 'First Blood',
                'title' => 'First Blood',
                'description' => 'Menyelesaikan ujian pertama kali.',
                'lore_text' => 'Langkah nyata menuju puncak intelektual.',
                'icon' => 'fas fa-fire',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#f97316',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'exam_count',
                'criteria_value' => '1',
                'criteria_data' => null,
                'xp_reward' => 50,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'quick_learner',
                'name' => 'Quick Learner',
                'title' => 'Quick Learner',
                'description' => 'Lulus ujian dengan skor di atas KKM.',
                'lore_text' => 'Paham strategi dasar.',
                'icon' => 'fas fa-bolt',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#facc15',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'final_score',
                'criteria_value' => '75',
                'criteria_data' => null,
                'xp_reward' => 100,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'perfect_score',
                'name' => 'Perfect Score',
                'title' => 'Perfect Score',
                'description' => 'Mendapatkan nilai 100 murni tanpa dongkrak.',
                'lore_text' => 'Langkah nyata menuju puncak intelektual.',
                'icon' => 'fas fa-star',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#eab308',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'final_score',
                'criteria_value' => '100',
                'criteria_data' => null,
                'xp_reward' => 200,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'consistency_king',
                'name' => 'Consistency King',
                'title' => 'Consistency King',
                'description' => 'Selesaikan 5 ujian secara berturut-turut.',
                'lore_text' => 'Ketekunan membuahkan hasil.',
                'icon' => 'fas fa-calendar-check',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#10b981',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'exam_count',
                'criteria_value' => '5',
                'criteria_data' => null,
                'xp_reward' => 200,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'night_owl',
                'name' => 'Night Owl',
                'title' => 'Night Owl',
                'description' => 'Mengumpulkan ujian setelah pukul 21:00 WIB.',
                'lore_text' => 'Langkah nyata menuju puncak intelektual.',
                'icon' => 'fas fa-moon',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#1e293b',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'submission_hour',
                'criteria_value' => '21',
                'criteria_data' => null,
                'xp_reward' => 100,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'social_media_king',
                'name' => 'Social Media King',
                'title' => 'Social Media King',
                'description' => 'Memperbarui identitas visual (Avatar Kustom).',
                'lore_text' => 'Langkah nyata menuju puncak intelektual.',
                'icon' => 'fas fa-camera',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#ec4899',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'custom_avatar',
                'criteria_value' => '1',
                'criteria_data' => null,
                'xp_reward' => 50,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'top_tier',
                'name' => 'Top Tier',
                'title' => 'Top Tier',
                'description' => 'Masuk ke dalam Top 10 Leaderboard Global.',
                'lore_text' => 'Melihat dunia dari puncak.',
                'icon' => 'fas fa-trophy',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#ef4444',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'leaderboard_rank',
                'criteria_value' => '10',
                'criteria_data' => null,
                'xp_reward' => 300,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'speed_runner',
                'name' => 'Speed Runner',
                'title' => 'Speed Runner',
                'description' => 'Selesaikan ujian dalam waktu kurang dari 50%.',
                'lore_text' => 'Cepat dan tepat.',
                'icon' => 'fas fa-running',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#06b6d4',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'completion_time_pct',
                'criteria_value' => '50',
                'criteria_data' => null,
                'xp_reward' => 200,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'academic_master',
                'name' => 'Academic Master',
                'title' => 'Academic Master',
                'description' => 'Miliki rata-rata skor di atas 90 dari 5 ujian.',
                'lore_text' => 'Penguasaan materi yang mutlak.',
                'icon' => 'fas fa-graduation-cap',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#8b5cf6',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'avg_score',
                'criteria_value' => '90',
                'criteria_data' => null,
                'xp_reward' => 500,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'comeback_kid',
                'name' => 'Comeback Kid',
                'title' => 'Comeback Kid',
                'description' => 'Tingkatkan skor lebih dari 20 poin dari sebelumnya.',
                'lore_text' => 'Bangkit lebih kuat.',
                'icon' => 'fas fa-chart-line',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#f43f5e',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'score_increase',
                'criteria_value' => '20',
                'criteria_data' => null,
                'xp_reward' => 150,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'loyal_student',
                'name' => 'Loyal Student',
                'title' => 'Loyal Student',
                'description' => 'Selesaikan total 20 ujian.',
                'lore_text' => 'Dedikasi tanpa batas.',
                'icon' => 'fas fa-heart',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#f9a8d4',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'exam_count',
                'criteria_value' => '20',
                'criteria_data' => null,
                'xp_reward' => 1000,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'first-90',
                'name' => 'FIRST 90',
                'title' => 'FIRST 90',
                'description' => 'dapat nilai 90 keatas pertama kali',
                'lore_text' => 'Semangat',
                'icon' => 'fas fa-star',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#64748b',
                'theme_color' => '#eab308',
                'glow_color' => '#000000',
                'criteria_type' => 'final_score',
                'criteria_value' => '90',
                'criteria_data' => '[]',
                'xp_reward' => 100,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'battle-arena-champion',
                'name' => 'Arena Champion',
                'title' => 'Gladiator Arena 🏆',
                'description' => 'Menjadi juara pertama dalam Battle Arena.',
                'lore_text' => 'Tunjukkan pada mereka siapa penguasa arena yang sebenarnya!',
                'icon' => 'fas fa-trophy',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#FFD700',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'arena_win_count',
                'criteria_value' => '1',
                'criteria_data' => null,
                'xp_reward' => 250,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'unstoppable',
                'name' => 'Unstoppable',
                'title' => 'Unstoppable',
                'description' => 'Lulus KKM 3 kali berturut-turut.',
                'lore_text' => 'Langkah nyata menuju puncak intelektual.',
                'icon' => 'fas fa-bolt',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#6366f1',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'consecutive_pass',
                'criteria_value' => '3',
                'criteria_data' => null,
                'xp_reward' => 150,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'early_bird',
                'name' => 'Early Bird',
                'title' => 'Early Bird',
                'description' => 'Menjadi siswa pertama yang submit di satu sesi ujian.',
                'lore_text' => 'Langkah nyata menuju puncak intelektual.',
                'icon' => 'fas fa-clock',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#22c55e',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'first_submit',
                'criteria_value' => '1',
                'criteria_data' => null,
                'xp_reward' => 300,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'the_flash',
                'name' => 'The Flash',
                'title' => 'The Flash',
                'description' => 'Lulus KKM dengan waktu < 50% dari durasi ujian.',
                'lore_text' => 'Langkah nyata menuju puncak intelektual.',
                'icon' => 'fas fa-wind',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#06b6d4',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'completion_time_pct',
                'criteria_value' => '50',
                'criteria_data' => null,
                'xp_reward' => 100,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'comeback_king',
                'name' => 'Comeback King',
                'title' => 'Comeback King',
                'description' => 'Kenaikan nilai > 30 poin dari ujian sebelumnya.',
                'lore_text' => 'Langkah nyata menuju puncak intelektual.',
                'icon' => 'fas fa-crown',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#8b5cf6',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'score_increase',
                'criteria_value' => '30',
                'criteria_data' => null,
                'xp_reward' => 250,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'hard_worker',
                'name' => 'Hard Worker',
                'title' => 'Hard Worker',
                'description' => 'Total menyelesaikan 10 ujian (akumulatif).',
                'lore_text' => 'Langkah nyata menuju puncak intelektual.',
                'icon' => 'fas fa-hammer',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#4b5563',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'exam_count',
                'criteria_value' => '10',
                'criteria_data' => null,
                'xp_reward' => 300,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'scholar_warrior',
                'name' => 'Scholar Warrior',
                'title' => 'Scholar Warrior',
                'description' => 'Rata-rata seluruh nilai ujian di atas 90.',
                'lore_text' => 'Langkah nyata menuju puncak intelektual.',
                'icon' => 'fas fa-graduation-cap',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#dc2626',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'avg_score',
                'criteria_value' => '90',
                'criteria_data' => null,
                'xp_reward' => 500,
                'is_active' => true,
                'is_secret' => 0,
            ],
            [
                'slug' => 'first_prestige',
                'name' => 'Prestige Pertama',
                'title' => 'The Awakened',
                'description' => 'Lakukan Prestige untuk pertama kalinya.',
                'lore_text' => 'Kelahiran kembali seorang master.',
                'icon' => 'fas fa-dna',
                'icon_type' => 'fa',
                'icon_path' => null,
                'color' => '#f43f5e',
                'theme_color' => null,
                'glow_color' => null,
                'criteria_type' => 'prestige_count',
                'criteria_value' => '1',
                'criteria_data' => null,
                'xp_reward' => 50,
                'is_active' => true,
                'is_secret' => 0,
            ],
        ];

        foreach ($achievements as $achievement) {
            Achievement::updateOrCreate(
                ['slug' => $achievement['slug']],
                $achievement
            );
        }
    }
}
