<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    /** @use HasFactory<\Database\Factories\UserFactory> */
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'name',
        'title_ahead',
        'title_behind',
        'email',
        'password',
        'nis',
        'jenjang',
        'grade',
        'is_active',
        'photo',
        'custom_avatar',
        'avatar_upload',
        'role',
        'total_exp',
        'current_level',
        'ui_theme',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var list<string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'is_active' => 'boolean',
            'is_signature_active' => 'boolean',
        ];
    }

    /**
     * Get exam attempts for this student.
     */
    public function examAttempts()
    {
        return $this->hasMany(ExamAttempt::class, 'student_id');
    }

    /**
     * Get achievements for this student.
     */
    public function achievements()
    {
        return $this->belongsToMany(Achievement::class, 'achievement_user')
            ->withPivot('achieved_at')
            ->withTimestamps();
    }

    /**
     * Get exam sessions for this student.
     */
    public function examSessions()
    {
        return $this->hasMany(ExamSession::class, 'student_id');
    }

    /**
     * The subjects assigned to the teacher.
     */
    public function subjects()
    {
        return $this->belongsToMany(Subject::class);
    }

    /**
     * Get tokens used by this student.
     */
    public function usedTokens()
    {
        return $this->hasMany(ExamToken::class, 'used_by');
    }

    /**
     * Get action logs performed by this admin.
     */
    public function actionLogs()
    {
        return $this->hasMany(ActionLog::class, 'admin_id');
    }



    /**
     * Get the avatar URL (Priority: custom > photo > default).
     */
    public function getAvatarUrlAttribute()
    {
        // 1. If student uploaded their own photo
        if ($this->avatar_upload) {
            return asset('storage/' . $this->avatar_upload);
        }

        // 2. If student chose an avatar from gallery or generated by Multiavatar
        if ($this->custom_avatar) {
            // Check if it's a seed (not a path/url)
            if ($this->is_avatar_seed) {
                // For client-side rendering, we don't return a URL.
                // Views should check for is_avatar_seed
                return null;
            }

            // Check if it's a multiavatar saved in storage (legacy support)
            if (str_starts_with($this->custom_avatar, 'avatars/multiavatar/')) {
                if (\Illuminate\Support\Facades\Storage::disk('public')->exists($this->custom_avatar)) {
                    return asset('storage/' . $this->custom_avatar);
                }
            }
        }

        // 3. Check for uploaded photo (Admin/Siswa)
        if ($this->photo && \Illuminate\Support\Facades\Storage::disk('public')->exists('profiles/' . $this->photo)) {
            return asset('storage/profiles/' . $this->photo);
        }

        // 4. Fallback to Global Default Student Avatar from Settings
        $globalDefault = \App\Models\Setting::get('default_student_avatar');
        if ($globalDefault && \Illuminate\Support\Facades\Storage::disk('public')->exists($globalDefault)) {
            return asset('storage/' . $globalDefault);
        }

        // 5. Return null (will trigger initials or Multiavatar in UI)
        return null;
    }

    public function getIsAvatarSeedAttribute(): bool
    {
        if (!$this->custom_avatar || $this->avatar_upload) {
            return false;
        }

        // A seed is a string without / or . (unlike paths like avatars/xxx.png or images/xxx.svg)
        return !str_contains($this->custom_avatar, '/') && !str_contains($this->custom_avatar, '.');
    }

    /**
     * Get the seed for Multiavatar generation (Priority: custom_avatar > name).
     */
    public function getAvatarSeedAttribute(): string
    {
        return $this->custom_avatar ?: $this->name;
    }

    /**
     * Get the photo URL for the student (Always formal photo).
     */
    public function getPhotoUrlAttribute(): string
    {
        if ($this->photo && \Illuminate\Support\Facades\Storage::disk('public')->exists('profiles/' . $this->photo)) {
            return asset('storage/profiles/' . $this->photo);
        }

        // Fallback to UI-Avatars
        return 'https://ui-avatars.com/api/?name=' . urlencode($this->name) . '&background=random&color=fff&size=400';
    }

    /**
     * Get the signature URL.
     */
    public function getSignatureUrlAttribute(): ?string
    {
        if ($this->signature && \Illuminate\Support\Facades\Storage::disk('public')->exists('signatures/' . $this->signature)) {
            return asset('storage/signatures/' . $this->signature);
        }

        return null;
    }

    /**
     * Get the student's level title.
     */
    public function getLevelTitleAttribute(): string
    {
        $level = $this->current_level;
        if ($level >= 31) return 'Grandmaster';
        if ($level >= 16) return 'Master';
        if ($level >= 6) return 'Scholar';
        return 'Newbie';
    }

    /**
     * Get the greeting based on title.
     */
    public function getDynamicGreetingAttribute(): string
    {
        $title = $this->level_title;
        $name = explode(' ', $this->name)[0];

        return match ($title) {
            'Scholar' => "Semangat belajarnya, Scholar $name! Selangkah lagi menuju Master.",
            'Master' => "Selamat datang kembali, Master $name. Fokus dan taklukkan hari ini!",
            'Grandmaster' => "Hormat kami, Grandmaster $name. Tunjukkan kelasmu di Leaderboard!",
            default => "Selamat berjuang, Newbie $name! Ayo mulai ujian pertamamu.",
        };
    }

    /**
     * Get the CSS classes for the avatar frame based on level.
     */
    public function getAvatarFrameClassAttribute(): string
    {
        $level = $this->current_level;
        
        if ($level >= 31) {
            return 'theme-active-frame theme-active-glow ring-4 ring-amber-500/30 frame-shine';
        }
        if ($level >= 16) {
            return 'theme-active-frame theme-active-glow border-purple-400 animate-pulse ring-4 ring-purple-500/20';
        }
        if ($level >= 6) {
            return 'theme-active-frame theme-active-glow border-blue-400 ring-4 ring-blue-500/20';
        }
        
        return 'border-slate-200';
    }

    /**
     * Get XP progress percentage (0-100).
     */
    public function getXpProgressPercentageAttribute(): int
    {
        return $this->total_exp % 100;
    }

    /**
     * Check if user has a custom avatar or photo set.
     */
    public function getHasAvatarAttribute()
    {
        // If it's a generated seed, we consider it having an avatar
        if ($this->is_avatar_seed && $this->avatar_seed) {
            return true;
        }

        // Check for physical file existence for custom uploads
        if ($this->avatar_upload && \Illuminate\Support\Facades\Storage::disk('public')->exists($this->avatar_upload)) {
            return true;
        }

        if ($this->photo && \Illuminate\Support\Facades\Storage::disk('public')->exists('profiles/' . $this->photo)) {
            return true;
        }

        // Check for Global Default Avatar from Setting
        $globalDefault = \App\Models\Setting::get('default_student_avatar');
        if ($globalDefault && \Illuminate\Support\Facades\Storage::disk('public')->exists($globalDefault)) {
            return true;
        }

        return false;
    }

    /**
     * Get the user's name initials.
     */
    public function getInitialsAttribute()
    {
        $words = explode(' ', $this->name);
        if (count($words) >= 2) {
            return strtoupper(substr($words[0], 0, 1) . substr($words[1], 0, 1));
        }
        return strtoupper(substr($this->name, 0, 2));
    }

    /**
     * Get formatted full name with titles.
     */
    public function getFullNameAttribute()
    {
        $name = $this->formatted_name;

        if ($this->title_ahead) {
            $name = $this->title_ahead . ' ' . $name;
        }

        if ($this->title_behind) {
            $name = $name . ', ' . $this->title_behind;
        }

        return $name;
    }

    /**
     * Get the name in Title Case (Capitalize first letter of each word).
     */
    public function getFormattedNameAttribute()
    {
        return ucwords(strtolower($this->name));
    }

    /**
     * Check if user is teacher or superadmin.
     */
    public function isAdmin(): bool
    {
        return in_array($this->role, ['superadmin', 'teacher']);
    }
}
